apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: haproxy-svc-templates
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: haproxy
    name: haproxy
  spec:
    ports:
    - name: 8880-tcp
      port: 8880
      protocol: TCP
      targetPort: 8880
    selector:
      app: haproxy
      deploymentconfig: haproxy
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
