apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: haproxy-is-templates
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/image.dockerRepositoryCheck: 2020-01-15T02:27:23Z
    creationTimestamp: null
    generation: 3
    labels:
      app: haproxy
    name: haproxy
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: amd64/haproxy:2.1.2
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/recsys/haproxy:2.1.2
      generation: 3
      importPolicy: {}
      name: 2.1.2
      referencePolicy:
        type: Source
    - annotations: null
      from:
        kind: DockerImage
        name: docker-registry.default.svc:5000/recsys/haproxy:latest
      generation: 3
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
