apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: mongodb-svc-templates
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: mongodb://{.spec.clusterIP}:{.spec.ports[?(.name=="mongo")].port}
    creationTimestamp: null
    labels:
      template: mongodb-persistent-template
    name: mongodb
    ownerReferences:
    - apiVersion: template.openshift.io/v1
      blockOwnerDeletion: true
      kind: TemplateInstance
      name: c3f29738-4da8-413e-9fe9-ade57af04c4e
      uid: a7f84114-35e3-11ea-b99a-fa163eb6547a
  spec:
    ports:
    - name: mongo
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      name: mongodb
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
