apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: redis-svc-templates
objects:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      template.openshift.io/expose-uri: redis://{.spec.clusterIP}:{.spec.ports[?(.name=="redis")].port}
    creationTimestamp: null
    labels:
      template: redis-persistent-template
    name: redis
    ownerReferences:
    - apiVersion: template.openshift.io/v1
      blockOwnerDeletion: true
      kind: TemplateInstance
      name: e9967c6e-d0e7-4dfe-9094-f3e7a8c7b12d
      uid: ea955604-35e5-11ea-b99a-fa163eb6547a
  spec:
    ports:
    - name: redis
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      name: redis
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
