apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: webenglish-dc-templates
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: webenglish
    name: webenglish
  spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
      app: webenglish
      deploymentconfig: webenglish
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: webenglish
          deploymentconfig: webenglish
      spec:
        containers:
        - env:
          - name: LANGUAGE
            value: en
          - name: NAME_LOG
            value: web_english
          envFrom:
          - secretRef:
              name: secret-with-environment-variables
          image: docker-registry.default.svc:5000/recsys/webenglish@sha256:dbfc01b7c8abb3cf63c9ef550422e6f5aa4aa2e042bb7bf2e8719b1d4af8658c
          imagePullPolicy: Always
          name: webenglish
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: 10m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /workplace/log
            name: log4webenglish
            subPath: log4webenglish
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: log4webenglish
          persistentVolumeClaim:
            claimName: logs
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - webenglish
        from:
          kind: ImageStreamTag
          name: webenglish:latest
          namespace: recsys
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
