apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: webfrench-dc-templates
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    generation: 1
    labels:
      app: webfrench
    name: webfrench
  spec:
    replicas: 1
    revisionHistoryLimit: 3
    selector:
      app: webfrench
      deploymentconfig: webfrench
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: webfrench
          deploymentconfig: webfrench
      spec:
        containers:
        - env:
          - name: NAME_LOG
            value: web_french
          - name: LANGUAGE
            value: fr
          envFrom:
          - secretRef:
              name: secret-with-environment-variables
          image: docker-registry.default.svc:5000/recsys/webfrench@sha256:e77dd2045395a8ac8ac333d7a751c5175c4c28db89d2b2dc245199755883dd27
          imagePullPolicy: Always
          name: webfrench
          ports:
          - containerPort: 8080
            protocol: TCP
          resources:
            limits:
              cpu: "1"
              memory: 2000Mi
            requests:
              cpu: 10m
              memory: 128Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /workplace/log
            name: log4webfrench
            subPath: log4webfrench
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - name: log4webfrench
          persistentVolumeClaim:
            claimName: logs
    test: false
    triggers:
    - imageChangeParams:
        automatic: true
        containerNames:
        - webfrench
        from:
          kind: ImageStreamTag
          name: webfrench:latest
          namespace: recsys
      type: ImageChange
    - type: ConfigChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
