apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: databases
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: rabbitmq
    name: rabbitmq
  spec:
    replicas: 1
    selector:
      app: rabbitmq
      deploymentconfig: rabbitmq
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: rabbitmq
          deploymentconfig: rabbitmq
      spec:
        containers:
        - image: rabbitmq@sha256:2195a2ecefac2bf8aeac045fd7e0f0872cb146e77248493773020b2ae15fc131
          imagePullPolicy: IfNotPresent
          name: rabbitmq
          ports:
          - containerPort: 4369
            protocol: TCP
          - containerPort: 5671
            protocol: TCP
          - containerPort: 5672
            protocol: TCP
          - containerPort: 25672
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbitmq-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: rabbitmq-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - rabbitmq
        from:
          kind: ImageStreamTag
          name: rabbitmq:3.8-rc
          namespace: myproject
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    generation: 1
    labels:
      app: redis
    name: redis
  spec:
    replicas: 1
    selector:
      app: redis
      deploymentconfig: redis
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: redis
          deploymentconfig: redis
      spec:
        containers:
        - image: redis@sha256:ee1d00c5250b5a886b09be2d5f9506add35dfb557f1ef37a7e4b8f0138f32956
          imagePullPolicy: Always
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: redis-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: redis-1
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - redis
        from:
          kind: ImageStreamTag
          name: redis:latest
          namespace: myproject
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2020-03-05T09:41:41Z
    creationTimestamp: null
    generation: 2
    labels:
      app: rabbitmq
    name: rabbitmq
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: rabbitmq:3.8-rc
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/myproject/rabbitmq:3.8-rc
      generation: 2
      importPolicy: {}
      name: 3.8-rc
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/image.dockerRepositoryCheck: 2020-03-05T09:43:50Z
    creationTimestamp: null
    generation: 2
    labels:
      app: redis
    name: redis
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/generated-by: OpenShiftWebConsole
        openshift.io/imported-from: redis
      from:
        kind: DockerImage
        name: 172.30.1.1:5000/myproject/redis:latest
      generation: 2
      importPolicy: {}
      name: latest
      referencePolicy:
        type: Source
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: rabbitmq
      openshift.io/deployment.name: rabbitmq-1
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/scc: restricted
    creationTimestamp: null
    generateName: rabbitmq-1-
    labels:
      app: rabbitmq
      deployment: rabbitmq-1
      deploymentconfig: rabbitmq
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: rabbitmq-1
      uid: 84eeeeed-5ec5-11ea-a050-0800279d113d
  spec:
    containers:
    - image: rabbitmq@sha256:2195a2ecefac2bf8aeac045fd7e0f0872cb146e77248493773020b2ae15fc131
      imagePullPolicy: IfNotPresent
      name: rabbitmq
      ports:
      - containerPort: 4369
        protocol: TCP
      - containerPort: 5671
        protocol: TCP
      - containerPort: 5672
        protocol: TCP
      - containerPort: 25672
        protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
          - KILL
          - MKNOD
          - SETGID
          - SETUID
        runAsUser: 1000140000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /var/lib/rabbitmq
        name: rabbitmq-1
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-264ps
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-n6822
    nodeName: localhost
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000140000
      seLinuxOptions:
        level: s0:c12,c4
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - emptyDir: {}
      name: rabbitmq-1
    - name: default-token-264ps
      secret:
        defaultMode: 420
        secretName: default-token-264ps
  status:
    phase: Pending
    qosClass: BestEffort
- apiVersion: v1
  kind: Pod
  metadata:
    annotations:
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: redis
      openshift.io/deployment.name: redis-1
      openshift.io/generated-by: OpenShiftWebConsole
      openshift.io/scc: restricted
    creationTimestamp: null
    generateName: redis-1-
    labels:
      app: redis
      deployment: redis-1
      deploymentconfig: redis
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicationController
      name: redis-1
      uid: d1ef932f-5ec5-11ea-a050-0800279d113d
  spec:
    containers:
    - image: redis@sha256:ee1d00c5250b5a886b09be2d5f9506add35dfb557f1ef37a7e4b8f0138f32956
      imagePullPolicy: Always
      name: redis
      ports:
      - containerPort: 6379
        protocol: TCP
      resources: {}
      securityContext:
        capabilities:
          drop:
          - KILL
          - MKNOD
          - SETGID
          - SETUID
        runAsUser: 1000140000
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
      - mountPath: /data
        name: redis-1
      - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
        name: default-token-264ps
        readOnly: true
    dnsPolicy: ClusterFirst
    imagePullSecrets:
    - name: default-dockercfg-n6822
    nodeName: localhost
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext:
      fsGroup: 1000140000
      seLinuxOptions:
        level: s0:c12,c4
    serviceAccount: default
    serviceAccountName: default
    terminationGracePeriodSeconds: 30
    volumes:
    - emptyDir: {}
      name: redis-1
    - name: default-token-264ps
      secret:
        defaultMode: 420
        secretName: default-token-264ps
  status:
    phase: Pending
    qosClass: BestEffort
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      openshift.io/deployer-pod.completed-at: 2020-03-05 09:43:07 +0000 UTC
      openshift.io/deployer-pod.created-at: 2020-03-05 09:41:42 +0000 UTC
      openshift.io/deployer-pod.name: rabbitmq-1-deploy
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: rabbitmq
      openshift.io/deployment.phase: Complete
      openshift.io/deployment.replicas: "1"
      openshift.io/deployment.status-reason: config change
      openshift.io/encoded-deployment-config: |
        {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"rabbitmq","namespace":"myproject","selfLink":"/apis/apps.openshift.io/v1/namespaces/myproject/deploymentconfigs/rabbitmq","uid":"81c93e44-5ec5-11ea-8af5-0800279d113d","resourceVersion":"1714190","generation":2,"creationTimestamp":"2020-03-05T09:41:36Z","labels":{"app":"rabbitmq"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["rabbitmq"],"from":{"kind":"ImageStreamTag","namespace":"myproject","name":"rabbitmq:3.8-rc"},"lastTriggeredImage":"rabbitmq@sha256:2195a2ecefac2bf8aeac045fd7e0f0872cb146e77248493773020b2ae15fc131"}}],"replicas":1,"test":false,"selector":{"app":"rabbitmq","deploymentconfig":"rabbitmq"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"rabbitmq","deploymentconfig":"rabbitmq"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"volumes":[{"name":"rabbitmq-1","emptyDir":{}}],"containers":[{"name":"rabbitmq","image":"rabbitmq@sha256:2195a2ecefac2bf8aeac045fd7e0f0872cb146e77248493773020b2ae15fc131","ports":[{"containerPort":4369,"protocol":"TCP"},{"containerPort":5671,"protocol":"TCP"},{"containerPort":5672,"protocol":"TCP"},{"containerPort":25672,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"rabbitmq-1","mountPath":"/var/lib/rabbitmq"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"IfNotPresent"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2020-03-05T09:41:36Z","lastTransitionTime":"2020-03-05T09:41:36Z","message":"Deployment config does not have minimum availability."}]}}
    creationTimestamp: null
    generation: 1
    labels:
      app: rabbitmq
      openshift.io/deployment-config.name: rabbitmq
    name: rabbitmq-1
    ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: rabbitmq
      uid: 81c93e44-5ec5-11ea-8af5-0800279d113d
  spec:
    replicas: 1
    selector:
      app: rabbitmq
      deployment: rabbitmq-1
      deploymentconfig: rabbitmq
    template:
      metadata:
        annotations:
          openshift.io/deployment-config.latest-version: "1"
          openshift.io/deployment-config.name: rabbitmq
          openshift.io/deployment.name: rabbitmq-1
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: rabbitmq
          deployment: rabbitmq-1
          deploymentconfig: rabbitmq
      spec:
        containers:
        - image: rabbitmq@sha256:2195a2ecefac2bf8aeac045fd7e0f0872cb146e77248493773020b2ae15fc131
          imagePullPolicy: IfNotPresent
          name: rabbitmq
          ports:
          - containerPort: 4369
            protocol: TCP
          - containerPort: 5671
            protocol: TCP
          - containerPort: 5672
            protocol: TCP
          - containerPort: 25672
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /var/lib/rabbitmq
            name: rabbitmq-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: rabbitmq-1
  status:
    replicas: 0
- apiVersion: v1
  kind: ReplicationController
  metadata:
    annotations:
      openshift.io/deployer-pod.completed-at: 2020-03-05 09:45:21 +0000 UTC
      openshift.io/deployer-pod.created-at: 2020-03-05 09:43:51 +0000 UTC
      openshift.io/deployer-pod.name: redis-1-deploy
      openshift.io/deployment-config.latest-version: "1"
      openshift.io/deployment-config.name: redis
      openshift.io/deployment.phase: Complete
      openshift.io/deployment.replicas: "1"
      openshift.io/deployment.status-reason: config change
      openshift.io/encoded-deployment-config: |
        {"kind":"DeploymentConfig","apiVersion":"apps.openshift.io/v1","metadata":{"name":"redis","namespace":"myproject","selfLink":"/apis/apps.openshift.io/v1/namespaces/myproject/deploymentconfigs/redis","uid":"c767a74d-5ec5-11ea-8af5-0800279d113d","resourceVersion":"1714756","generation":2,"creationTimestamp":"2020-03-05T09:43:33Z","labels":{"app":"redis"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"strategy":{"type":"Rolling","rollingParams":{"updatePeriodSeconds":1,"intervalSeconds":1,"timeoutSeconds":600,"maxUnavailable":"25%","maxSurge":"25%"},"resources":{},"activeDeadlineSeconds":21600},"triggers":[{"type":"ConfigChange"},{"type":"ImageChange","imageChangeParams":{"automatic":true,"containerNames":["redis"],"from":{"kind":"ImageStreamTag","namespace":"myproject","name":"redis:latest"},"lastTriggeredImage":"redis@sha256:ee1d00c5250b5a886b09be2d5f9506add35dfb557f1ef37a7e4b8f0138f32956"}}],"replicas":1,"test":false,"selector":{"app":"redis","deploymentconfig":"redis"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"redis","deploymentconfig":"redis"},"annotations":{"openshift.io/generated-by":"OpenShiftWebConsole"}},"spec":{"volumes":[{"name":"redis-1","emptyDir":{}}],"containers":[{"name":"redis","image":"redis@sha256:ee1d00c5250b5a886b09be2d5f9506add35dfb557f1ef37a7e4b8f0138f32956","ports":[{"containerPort":6379,"protocol":"TCP"}],"resources":{},"volumeMounts":[{"name":"redis-1","mountPath":"/data"}],"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","imagePullPolicy":"Always"}],"restartPolicy":"Always","terminationGracePeriodSeconds":30,"dnsPolicy":"ClusterFirst","securityContext":{},"schedulerName":"default-scheduler"}}},"status":{"latestVersion":1,"observedGeneration":1,"replicas":0,"updatedReplicas":0,"availableReplicas":0,"unavailableReplicas":0,"details":{"message":"config change","causes":[{"type":"ConfigChange"}]},"conditions":[{"type":"Available","status":"False","lastUpdateTime":"2020-03-05T09:43:33Z","lastTransitionTime":"2020-03-05T09:43:33Z","message":"Deployment config does not have minimum availability."}]}}
    creationTimestamp: null
    generation: 1
    labels:
      app: redis
      openshift.io/deployment-config.name: redis
    name: redis-1
    ownerReferences:
    - apiVersion: apps.openshift.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: DeploymentConfig
      name: redis
      uid: c767a74d-5ec5-11ea-8af5-0800279d113d
  spec:
    replicas: 1
    selector:
      app: redis
      deployment: redis-1
      deploymentconfig: redis
    template:
      metadata:
        annotations:
          openshift.io/deployment-config.latest-version: "1"
          openshift.io/deployment-config.name: redis
          openshift.io/deployment.name: redis-1
          openshift.io/generated-by: OpenShiftWebConsole
        creationTimestamp: null
        labels:
          app: redis
          deployment: redis-1
          deploymentconfig: redis
      spec:
        containers:
        - image: redis@sha256:ee1d00c5250b5a886b09be2d5f9506add35dfb557f1ef37a7e4b8f0138f32956
          imagePullPolicy: Always
          name: redis
          ports:
          - containerPort: 6379
            protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - mountPath: /data
            name: redis-1
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        volumes:
        - emptyDir: {}
          name: redis-1
  status:
    replicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: rabbitmq
    name: rabbitmq
  spec:
    ports:
    - name: 4369-tcp
      port: 4369
      protocol: TCP
      targetPort: 4369
    - name: 5671-tcp
      port: 5671
      protocol: TCP
      targetPort: 5671
    - name: 5672-tcp
      port: 5672
      protocol: TCP
      targetPort: 5672
    - name: 25672-tcp
      port: 25672
      protocol: TCP
      targetPort: 25672
    selector:
      deploymentconfig: rabbitmq
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftWebConsole
    creationTimestamp: null
    labels:
      app: redis
    name: redis
  spec:
    ports:
    - name: 6379-tcp
      port: 6379
      protocol: TCP
      targetPort: 6379
    selector:
      deploymentconfig: redis
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
